{% set name = "sunraster" %}
{% set version = "0.7.0" %}
{% set sha256 = "7f32ab0478ebe1fc5ea2c440e4546f8c62417c125eca32343143e454b59e2486" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.5.0
    - ndcube >=2.3.0
    - sunpy >=7.0.0
    - mpl_animators
    - astropy-base >=6.1.0
    - numpy >=1.26.0

test:
  requires:
    - python {{ python_min }}
    - pytest-astropy

  imports:
    - sunraster
    - sunraster.tests

  commands:
    - pytest --pyargs sunraster

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: A package providing instrument-agnostic data classes for manipulating solar spectrogram data.
  license_family: BSD
  dev_url: https://github.com/sunpy/sunraster
  doc_url: https://sunraster.readthedocs.io/

extra:
  recipe-maintainers:
    - DanRyanIrish
    - Cadair
    - nabobalis
    - wtbarnes
