{% set name = "sunraster" %}
{% set version = "0.4.0" %}
{% set sha256 = "0d02b572deeee991f43e6f224b9e982ba8e9dbce59c332a373db8a5dd904729f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - matplotlib-base >=3.3.0
    - ndcube >=2.0.1
    - sunpy >=3.0.0
    - mpl_animators

test:
  requires:
    - pytest-astropy

  imports:
    - sunraster
    - sunraster.tests

  commands:
    - pytest --pyargs sunraster

about:
  home: http://sunpy.org
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: A package providing instrument-agnostic data classes for manipulating solar spectrogram data.
  license_family: BSD
  dev_url: https://github.com/sunpy/sunraster
  doc_url: https://sunraster.readthedocs.io/

extra:
  recipe-maintainers:
    - DanRyanIrish
    - Cadair
